"""Tests for processiq.export.summary."""

from processiq.export.summary import export_insight_markdown, export_insight_text
from processiq.models import AnalysisInsight


class TestExportInsightText:
    def test_contains_header(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "PROCESSIQ ANALYSIS REPORT" in result

    def test_contains_summary_section(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "SUMMARY" in result
        assert "5-step order process" in result

    def test_contains_issues_section(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "ISSUES IDENTIFIED (1)" in result
        assert "Redundant approvals" in result

    def test_contains_recommendations_section(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "RECOMMENDATIONS (1)" in result
        assert "Consolidate approvals" in result

    def test_contains_core_value_section(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "CORE VALUE WORK" in result

    def test_contains_footer(self, sample_insight):
        result = export_insight_text(sample_insight)
        assert "Generated by ProcessIQ" in result

    def test_empty_issues(self):
        insight = AnalysisInsight(process_summary="Empty process")
        result = export_insight_text(insight)
        assert "No significant issues identified" in result

    def test_empty_recommendations(self):
        insight = AnalysisInsight(process_summary="Empty process")
        result = export_insight_text(insight)
        assert "No recommendations generated" in result


class TestExportInsightMarkdown:
    def test_has_heading(self, sample_insight):
        result = export_insight_markdown(sample_insight)
        assert "# ProcessIQ Analysis Report" in result

    def test_issues_table(self, sample_insight):
        result = export_insight_markdown(sample_insight)
        # Markdown table header
        assert "| # | Issue | Severity |" in result

    def test_recommendations_section(self, sample_insight):
        result = export_insight_markdown(sample_insight)
        assert "## Recommendations" in result

    def test_contains_footer(self, sample_insight):
        result = export_insight_markdown(sample_insight)
        assert "Generated by ProcessIQ" in result

    def test_empty_issues(self):
        insight = AnalysisInsight(process_summary="Minimal")
        result = export_insight_markdown(insight)
        assert "No significant issues identified" in result
