"""Summary text export functionality for ProcessIQ analysis results."""

import logging
from datetime import UTC, datetime

from processiq.models import AnalysisResult
from processiq.models.insight import AnalysisInsight

logger = logging.getLogger(__name__)


def export_summary_text(result: AnalysisResult) -> str:
    """Export analysis result as formatted text summary.

    Suitable for copying to documents, emails, or reports.

    Args:
        result: Complete analysis result.

    Returns:
        Formatted text summary.
    """
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("PROCESSIQ ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Process: {result.process_name}")
    lines.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"Overall Confidence: {result.overall_confidence * 100:.0f}%")
    lines.append("")

    # Executive Summary
    lines.append("-" * 60)
    lines.append("EXECUTIVE SUMMARY")
    lines.append("-" * 60)
    lines.append(result.summary if result.summary else "No summary available.")
    lines.append("")

    # Bottlenecks
    lines.append("-" * 60)
    lines.append(f"BOTTLENECKS IDENTIFIED ({len(result.bottlenecks)})")
    lines.append("-" * 60)
    if result.bottlenecks:
        for i, b in enumerate(result.bottlenecks, 1):
            lines.append(f"{i}. {b.step_name}")
            lines.append(f"   Severity: {b.severity.value.upper()}")
            lines.append(f"   Impact Score: {b.impact_score:.2f}")
            lines.append(f"   Reason: {b.reason}")
            if b.downstream_impact:
                lines.append(f"   Affects: {', '.join(b.downstream_impact)}")
            lines.append("")
    else:
        lines.append("No significant bottlenecks identified.")
        lines.append("")

    # Recommendations
    lines.append("-" * 60)
    lines.append(f"RECOMMENDATIONS ({len(result.suggestions)})")
    lines.append("-" * 60)
    if result.suggestions:
        for i, s in enumerate(result.suggestions, 1):
            lines.append(f"{i}. {s.title}")
            lines.append(
                f"   Type: {s.suggestion_type.value.replace('_', ' ').title()}"
            )
            lines.append(f"   Target: {s.bottleneck_step}")
            lines.append(f"   Description: {s.description}")
            lines.append(f"   Estimated Cost: ${s.estimated_cost:,.0f}")

            if s.roi:
                lines.append("   ROI Estimate:")
                lines.append(f"      Pessimistic: ${s.roi.pessimistic:,.0f}/year")
                lines.append(f"      Likely: ${s.roi.likely:,.0f}/year")
                lines.append(f"      Optimistic: ${s.roi.optimistic:,.0f}/year")
                lines.append(f"      Confidence: {s.roi.confidence * 100:.0f}%")
                if s.roi.payback_months:
                    lines.append(f"      Payback: {s.roi.payback_months:.1f} months")
                lines.append("   Assumptions:")
                for assumption in s.roi.assumptions:
                    lines.append(f"      - {assumption}")

            if s.implementation_steps:
                lines.append("   Implementation Steps:")
                for step in s.implementation_steps:
                    lines.append(f"      - {step}")
            lines.append("")
    else:
        lines.append("No recommendations generated.")
        lines.append("")

    # Data Gaps
    if result.data_gaps:
        lines.append("-" * 60)
        lines.append("DATA GAPS (would improve analysis)")
        lines.append("-" * 60)
        for gap in result.data_gaps:
            lines.append(f"- {gap}")
        lines.append("")

    # Footer
    lines.append("=" * 60)
    lines.append("Generated by ProcessIQ - AI-Powered Process Optimization")
    lines.append("=" * 60)

    logger.info("Generated text summary for process: %s", result.process_name)
    return "\n".join(lines)


def export_summary_markdown(result: AnalysisResult) -> str:
    """Export analysis result as markdown summary.

    Suitable for documentation or GitHub issues.

    Args:
        result: Complete analysis result.

    Returns:
        Markdown formatted summary.
    """
    lines = []

    # Header
    lines.append(f"# ProcessIQ Analysis: {result.process_name}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Overall Confidence:** {result.overall_confidence * 100:.0f}%")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(result.summary if result.summary else "*No summary available.*")
    lines.append("")

    # Bottlenecks
    lines.append(f"## Bottlenecks Identified ({len(result.bottlenecks)})")
    lines.append("")
    if result.bottlenecks:
        lines.append("| Step | Severity | Impact | Reason |")
        lines.append("|------|----------|--------|--------|")
        for b in result.bottlenecks:
            lines.append(
                f"| {b.step_name} | {b.severity.value.upper()} | {b.impact_score:.2f} | {b.reason} |"
            )
        lines.append("")
    else:
        lines.append("*No significant bottlenecks identified.*")
        lines.append("")

    # Recommendations
    lines.append(f"## Recommendations ({len(result.suggestions)})")
    lines.append("")
    if result.suggestions:
        for i, s in enumerate(result.suggestions, 1):
            lines.append(f"### {i}. {s.title}")
            lines.append("")
            lines.append(
                f"- **Type:** {s.suggestion_type.value.replace('_', ' ').title()}"
            )
            lines.append(f"- **Target:** {s.bottleneck_step}")
            lines.append(f"- **Estimated Cost:** ${s.estimated_cost:,.0f}")
            lines.append("")
            lines.append(s.description)
            lines.append("")

            if s.roi:
                lines.append("**ROI Estimate:**")
                lines.append("")
                lines.append("| Scenario | Annual Value |")
                lines.append("|----------|-------------|")
                lines.append(f"| Pessimistic | ${s.roi.pessimistic:,.0f} |")
                lines.append(f"| Likely | ${s.roi.likely:,.0f} |")
                lines.append(f"| Optimistic | ${s.roi.optimistic:,.0f} |")
                lines.append("")
                lines.append(f"*Confidence: {s.roi.confidence * 100:.0f}%*")
                lines.append("")
                if s.roi.assumptions:
                    lines.append("**Assumptions:**")
                    for assumption in s.roi.assumptions:
                        lines.append(f"- {assumption}")
                    lines.append("")
    else:
        lines.append("*No recommendations generated.*")
        lines.append("")

    # Data Gaps
    if result.data_gaps:
        lines.append("## Data Gaps")
        lines.append("")
        lines.append("The following information would improve analysis accuracy:")
        lines.append("")
        for gap in result.data_gaps:
            lines.append(f"- {gap}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by ProcessIQ - AI-Powered Process Optimization*")

    logger.info("Generated markdown summary for process: %s", result.process_name)
    return "\n".join(lines)


def export_insight_text(insight: AnalysisInsight) -> str:
    """Export AnalysisInsight as formatted text summary.

    Args:
        insight: LLM-generated analysis insight.

    Returns:
        Formatted text summary.
    """
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("PROCESSIQ ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary
    lines.append("-" * 60)
    lines.append("SUMMARY")
    lines.append("-" * 60)
    lines.append(insight.process_summary)
    lines.append("")

    # Issues
    lines.append("-" * 60)
    lines.append(f"ISSUES IDENTIFIED ({len(insight.issues)})")
    lines.append("-" * 60)
    if insight.issues:
        for i, issue in enumerate(insight.issues, 1):
            lines.append(f"{i}. {issue.title}")
            lines.append(f"   Severity: {issue.severity.upper()}")
            lines.append(f"   {issue.description}")
            if issue.affected_steps:
                lines.append(f"   Affects: {', '.join(issue.affected_steps)}")
            if issue.root_cause_hypothesis:
                lines.append(f"   Root cause: {issue.root_cause_hypothesis}")
            lines.append("")
    else:
        lines.append("No significant issues identified.")
        lines.append("")

    # Recommendations
    lines.append("-" * 60)
    lines.append(f"RECOMMENDATIONS ({len(insight.recommendations)})")
    lines.append("-" * 60)
    if insight.recommendations:
        for i, rec in enumerate(insight.recommendations, 1):
            lines.append(f"{i}. {rec.title}")
            lines.append(f"   Addresses: {rec.addresses_issue}")
            lines.append(f"   Feasibility: {rec.feasibility}")
            lines.append(f"   {rec.description}")
            if rec.expected_benefit:
                lines.append(f"   Expected benefit: {rec.expected_benefit}")
            if rec.risks:
                lines.append("   Risks:")
                for risk in rec.risks:
                    lines.append(f"      - {risk}")
            if rec.concrete_next_steps:
                lines.append("   Next steps:")
                for step in rec.concrete_next_steps:
                    lines.append(f"      - {step}")
            lines.append("")
    else:
        lines.append("No recommendations generated.")
        lines.append("")

    # Core value work
    if insight.not_problems:
        lines.append("-" * 60)
        lines.append(f"CORE VALUE WORK ({len(insight.not_problems)})")
        lines.append("-" * 60)
        for np in insight.not_problems:
            lines.append(f"- {np.step_name}: {np.why_not_a_problem}")
        lines.append("")

    # Patterns
    if insight.patterns:
        lines.append("-" * 60)
        lines.append("PATTERNS DETECTED")
        lines.append("-" * 60)
        for pattern in insight.patterns:
            lines.append(f"- {pattern}")
        lines.append("")

    # Caveats
    if insight.confidence_notes:
        lines.append("-" * 60)
        lines.append("CAVEATS")
        lines.append("-" * 60)
        lines.append(insight.confidence_notes)
        lines.append("")

    # Footer
    lines.append("=" * 60)
    lines.append("Generated by ProcessIQ - AI-Powered Process Optimization")
    lines.append("=" * 60)

    logger.info("Generated text summary from insight")
    return "\n".join(lines)


def export_insight_markdown(insight: AnalysisInsight) -> str:
    """Export AnalysisInsight as markdown summary.

    Args:
        insight: LLM-generated analysis insight.

    Returns:
        Markdown formatted summary.
    """
    lines = []

    # Header
    lines.append("# ProcessIQ Analysis Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(insight.process_summary)
    lines.append("")

    # Issues
    lines.append(f"## Issues Identified ({len(insight.issues)})")
    lines.append("")
    if insight.issues:
        lines.append("| # | Issue | Severity | Affected Steps |")
        lines.append("|---|-------|----------|----------------|")
        for i, issue in enumerate(insight.issues, 1):
            steps = ", ".join(issue.affected_steps) if issue.affected_steps else "-"
            lines.append(
                f"| {i} | {issue.title} | {issue.severity.upper()} | {steps} |"
            )
        lines.append("")
        for i, issue in enumerate(insight.issues, 1):
            lines.append(f"### {i}. {issue.title}")
            lines.append("")
            lines.append(issue.description)
            if issue.root_cause_hypothesis:
                lines.append("")
                lines.append(f"**Root cause hypothesis:** {issue.root_cause_hypothesis}")
            if issue.evidence:
                lines.append("")
                lines.append("**Evidence:**")
                for ev in issue.evidence:
                    lines.append(f"- {ev}")
            lines.append("")
    else:
        lines.append("*No significant issues identified.*")
        lines.append("")

    # Recommendations
    lines.append(f"## Recommendations ({len(insight.recommendations)})")
    lines.append("")
    if insight.recommendations:
        for i, rec in enumerate(insight.recommendations, 1):
            lines.append(f"### {i}. {rec.title}")
            lines.append("")
            lines.append(f"- **Addresses:** {rec.addresses_issue}")
            lines.append(f"- **Feasibility:** {rec.feasibility}")
            if rec.expected_benefit:
                lines.append(f"- **Expected benefit:** {rec.expected_benefit}")
            lines.append("")
            lines.append(rec.description)
            if rec.risks:
                lines.append("")
                lines.append("**Risks:**")
                for risk in rec.risks:
                    lines.append(f"- {risk}")
            if rec.concrete_next_steps:
                lines.append("")
                lines.append("**Next steps:**")
                for j, step in enumerate(rec.concrete_next_steps, 1):
                    lines.append(f"{j}. {step}")
            lines.append("")
    else:
        lines.append("*No recommendations generated.*")
        lines.append("")

    # Core value work
    if insight.not_problems:
        lines.append("## Core Value Work")
        lines.append("")
        lines.append("*These steps may look like bottlenecks but are where real value is created:*")
        lines.append("")
        for np in insight.not_problems:
            lines.append(f"- **{np.step_name}:** {np.why_not_a_problem}")
        lines.append("")

    # Patterns
    if insight.patterns:
        lines.append("## Patterns Detected")
        lines.append("")
        for pattern in insight.patterns:
            lines.append(f"- {pattern}")
        lines.append("")

    # Caveats
    if insight.confidence_notes:
        lines.append("## Caveats")
        lines.append("")
        lines.append(insight.confidence_notes)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by ProcessIQ - AI-Powered Process Optimization*")

    logger.info("Generated markdown summary from insight")
    return "\n".join(lines)
